version: '3'

services:
  app:
    container_name: "app"
    build: "./docker/go-dev"
    ports:
      - "80:8080"
      - "5002:5002"
    volumes:
      - ".:${GO_PROJECT_DIR}"
      - "$GOPATH/src:/go/src"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/app"