version: "3"

services:
  app-dev:
    container_name: "app-dev"
    build: "./docker/go-dev"
    # image: mxgn/url-shrtnr
    ports:
      - 80:8080
    volumes:
      - .:${GO_PROJECT_DIR}
      - $GOPATH/src:/go/src
      - ./www:/var/www
    links:
      - pgdb
    environment:
      GO_WORK_DIR: ${GO_PROJECT_DIR}/app

      APP_PORT: 8080
      APP_STATIC_DIR: /var/www/
      APP_PG_HOST: pgdb
      APP_PG_PORT: 5432
      APP_PG_USER: postgres
      APP_PG_DBNAME: pgdb

  pgdb:
    container_name: pgdb
    image: squbs/postgres-10.5-alpine
    restart: always
    ports:
      - 5432:5432
