version: "3"

services:
  app:
    container_name: "app"
    build: "./docker/go-dev"
    ports:
      - 80:8080
      - 5002:5002
    volumes:
      - .:${GO_PROJECT_DIR}
      - $GOPATH/src:/go/src
    links:
      - postgres
    environment:
      PORT: 8080
      # REDIS_URL: redis:6379
      GO_WORK_DIR: ${GO_PROJECT_DIR}/app
      PG_URL: postgres:5432

  # redis:
  #   container_name: redis
  #   image: redis:alpine
  #   volumes:
  #     - ./data/redis:/data

  postgres:
    container_name: postgres
    image: squbs/postgres-10.5-alpine
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - postgres_database:/var/lib/postgresql/data:Z
    # environment:
    #   POSTGRES_USER: pguser
    #   POSTGRES_PASSWORD: pguser
    #   POSTGRES_DB: pgdb

# volumes:
#   postgres_database:
#     external: true
