version: '3'

services:
  app:
    container_name: "app"
    build: "./docker/go-dev"
    ports:
      - "8080:8080"
    volumes:
      - ".:${GO_PROJECT_DIR}"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/app"