version: "3"

services:
  app-dev:
    container_name: "app-dev"
    build: "./docker/go-dev"
    # image: mxgn/url-shrtnr
    ports:
      - 80:8080
      - 5002:5002
    volumes:
      - .:${GO_PROJECT_DIR}
      - $GOPATH/src:/go/src
      - ./www:/var/www
    links:
      - pgdb
    environment:
      PORT: 8080
      STATIC_DIR: /var/www/
      GO_WORK_DIR: ${GO_PROJECT_DIR}/app
      PG_HOST: pgdb
      PG_PORT: 5432
      PG_USER: postgres
      PG_DBNAME: pgdb

  pgdb:
    container_name: pgdb
    image: squbs/postgres-10.5-alpine
    restart: always
    ports:
      - 5432:5432
