version: "3"

services:
  app:
    container_name: "app"
    build: "./docker/go-prod"
    ports:
      - 80:80
      - 5002:5002
    volumes:
      - .:${GO_PROJECT_DIR}
      - $GOPATH/src:/go/src
      - ./www:/var/www
    links:
      - pgdb
    environment:
      ENVIRONMENT: PROD
      PORT: 80
      # REDIS_URL: redis:6379
      GO_WORK_DIR: ${GO_PROJECT_DIR}/app
      PG_HOST: pgdb
      PG_PORT: 5432
      PG_USER: postgres
      PG_DBNAME: pgdb
      # PG_PASS: pguser

  # redis:
  #   container_name: redis
  #   image: redis:alpine
  #   volumes:
  #     - ./data/redis:/data

  pgdb:
    container_name: pgdb
    image: squbs/postgres-10.5-alpine
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - postgres_database:/var/lib/postgresql/data:Z
    # environment:
    #   POSTGRES_USER: pguser
    #   POSTGRES_PASSWORD: pguser
    #   POSTGRES_DB: pgdb

# volumes:
#   postgres_database:
#     external: true
