version: "3"

services:
  app:
    container_name: "app"
    image: mxgn/url-shrtnr
    ports:
      - 80:8080
      - 5002:5002
    links:
      - pgdb
    environment:
      ENVIRONMENT: PROD
      PORT: 8080
      PG_HOST: pgdb
      PG_PORT: 5432
      PG_USER: postgres
      PG_DBNAME: pgdb

  pgdb:
    container_name: pgdb
    image: squbs/postgres-10.5-alpine
    restart: always
    ports:
      - 5432:5432
